version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: build_yourself_nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Windows/Mac to access host
    depends_on:
      - backend
    networks:
      - build_yourself_network_dev

  postgres:
    image: postgres:15-alpine
    container_name: build_yourself_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - build_yourself_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: build_yourself_redis_dev
    restart: unless-stopped
    volumes:
      - redis_data_dev:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - build_yourself_network_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: build_yourself_api_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/migrations/__pycache__
      - /app/migrations/versions/__pycache__
      - backend_logs_dev:/app/logs
    ports:
      - "${API_PORT}:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - build_yourself_network_dev

volumes:
  postgres_data_dev:
  redis_data_dev:
  backend_logs_dev:

networks:
  build_yourself_network_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
